services:
  babchu-service:
    build: .
    container_name: babchu-service
    expose:
      - "8080"
    env_file:
      - .env
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

  nginx:
    image: nginx:alpine
    container_name: babchu-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - babchu-service

  db:
    image: mysql:8.0
    container_name: prod_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    expose:
      - "3306"
    volumes:
      - ~/babchu_mysql_data:/var/lib/mysql


